#!/usr/bin/perl

my %local = (
	map { split / +/, $_, 2 }
	map { chomp; $_ }
	`Meta/topics --format='%(refname:lstrip=2) %(objectname)'`
);
my %remote = (
	map { split / /, $_, 2 }
	grep { m{/} }
	map { chomp; $_ }
	`git for-each-ref --format='%(refname:lstrip=3) %(objectname)' refs/remotes/github`
);

my @push = grep { !$remote{$_} } (sort keys(%local));
my @prune = grep { !$local{$_} } (sort keys(%remote));
my @unmatched = grep { $remote{$_} && $remote{$_} ne $local{$_} } (sort keys(%local));

if (grep { $_ eq "--stale" } @ARGV) {
	print "PUSH:$_\n" foreach @push;
	print "PRUNE:$_\n" foreach @prune;
	if (@unmatched > 3) {
		print "PUSH:all\n";
	} else {
		print "PUSH:$_\n" foreach @unmatched;
	}
	exit 0;
}
elsif (grep { $_ eq "--push" } @ARGV) {
	print "$_\n" for @push;
	print ":$_\n" for @prune;
	exit 0;
}

if (@push) {
	print "Local branches that need pushed:\n";
	print $_, "\n" foreach @push;
}
if (@prune) {
	print "\n" if @push;
	print "Remote branches that need pruned:\n";
	print $_, "\n" foreach @prune;
}
