#!/bin/sh

show() {
	printf '%30s: %s\n' "$1" "$2"
}

check_merge() {
	if test -z "`git cherry $2 $1 | grep -v ^-`"; then
		show $1 "merged to $2"
		return 0
	fi
	return 1
}

check_seen=
case "$1" in
--seen)
	check_seen=t
	;;
esac

for i in `Meta/topics -t`; do
	case "$i" in
	*-wip|*-stale)
		continue
		;;
	esac

	check_merge $i origin/master ||
	check_merge $i origin/next ||
	{ test -n "$check_seen" && check_merge $i origin/seen; } ||
	show $i 'not merged'
done
exit 0
