#!/bin/bash

show() {
	printf '%30s: %s\n' "$1" "$2"
}

patch_ids() {
	git rev-list origin/master..$1 |
	git diff-tree --stdin -p |
	git patch-id |
	cut -d' ' -f1 |
	sort
}

check_merge() {
	local lpids=$2.patch-ids
	local rpids=${1/\//-}.patch-ids

	if ! test -e $lpids; then
		patch_ids origin/$2 >$lpids
	fi
	if ! test -e $rpids; then
		patch_ids $1 >$rpids
	fi

	case "$(comm -123 --total --output-delimiter=, $rpids $lpids)" in
	0,*,0,total)
		# no patches in topic
		return 0
		;;
	*,*,0,total)
		# nothing merged
		return 1
		;;
	0,*,*,total)
		# completely merged
		show $1 "merged to $2"
		return 0
		;;
	*)
		# partially merged
		show $1 "merged to $2 (partial)"
		return 0
	esac
}

check_seen=
check_jch=
while test $# -gt 0; do
	case "$1" in
	--seen)
		check_seen=t
		;;
	--jch)
		check_jch=t
		;;
	*)
		echo >&2 "unknown option: $1"
		exit 1
		;;
	esac
	shift
done

for i in `Meta/topics -t`; do
	case "$i" in
	*-wip|*-stale)
		continue
		;;
	esac

	check_merge $i master ||
	check_merge $i next ||
	{ test -n "$check_jch" && check_merge $i jch; } ||
	{ test -n "$check_seen" && check_merge $i seen; } ||
	show $i 'not merged'
done
rm -f *.patch-ids
exit 0
