#!/bin/sh

export GIT_EDITOR
GIT_EDITOR=:

cmd=
upstream=
while test $# -gt 0; do
	case "$1" in
	-c) cmd='git test run -t compile' ;;
	-t) cmd="make -j16 && (cd t && ./t${2#t}-*.sh)"; shift ;;
	-x) cmd=$2; shift ;;
	-u) upstream=$2; shift ;;
	--retest) cmd='git test run --retest HEAD' ;;
	--edit) unset GIT_EDITOR ;;
	*) break ;;
	esac
	shift
done

if test $# -gt 0; then
	cmd=$*
fi

if test -z "$cmd"; then
	cmd='git test run HEAD'
fi

if test -z "$upstream"; then
  upstream=`git rev-parse --symbolic-full-name @{u} 2>/dev/null`
fi
git rebase -i -x "$cmd" "${upstream:-origin}"
