#!/bin/sh

eval "$(
	git rev-parse --parseopt -- "$@" <<-\EOF || echo exit $?
	Meta/topics [options]
	--
	v           show subject of tip commit
	u           show upstream branches
	t           sort by authordate
	format=s    custom output format
	EOF
)"

format='%(refname:short)'
sortby=refname
while test $# -gt 0; do
	case "$1" in
	-v) format='%(refname:short) %(subject)' ;;
	-t) sortby=-authordate ;;
	-u) format='%(refname:short) %(upstream:short)' ;;
	--format) format=$2; shift ;;
	 *) break ;;
	esac
	shift
done

git for-each-ref --sort=$sortby --format="$format" refs/heads |
egrep '^[a-z]*/' |
perl -pe '
  s/(\S+) /$& . " " x (30 - length($1))/e; # line up subjects
  s/^(.{79}).*/$1/; # truncate long lines
'
